name = "pipelib"
description = "Reusable pipeline components library"
version = "1.0.2"

authors = ["A Bit of Help, Inc. - Michael Gardner"]
maintainers = ["A Bit of Help, Inc. - Michael Gardner <mjgardner@abitofhelp.com>"]
maintainers-logins = ["abitofhelp"]
licenses = "MIT"
website = "https://github.com/abitofhelp/pipelib_ada"
tags = ["pipeline", "stream", "data", "ada2022"]

[configuration]
auto_gpr_with = true

[[depends-on]]
gnat = "*"
abohlib = "*"

[[pins]]
abohlib = { path='../abohlib' }

[build-profiles]
"*" = "release"

[build-switches]
"*".style_checks = ["-gnatyM120", "-gnatyx", "-gnatye", "-gnatyr", "-gnatyn", "-gnatyu", "-gnatyO"]
"*".contracts = "yes"
"*".runtime_checks = "everything"

[[depends-on]]
sha2 = "^2.0.0"
