# .github/workflows/check-file-size.yml
name: Check File Size

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    env:
      MAX_SIZE: '2097152'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to check all files

      - name: Check for large files
        run: |
          # Get list of files changed in this push/PR
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base_sha="${{ github.event.pull_request.base.sha }}"
          else
            base_sha="${{ github.event.before }}"
          fi

          # Skip if base_sha is empty or all zeros
          if [ -z "$base_sha" ] || [ "$base_sha" = "0000000000000000000000000000000000000000" ]; then
            echo "Initial commit. Skipping changed files check."
            exit 0
          fi
          
          echo "Checking for files larger than $(($MAX_SIZE / 1024 / 1024))MB..."
          
          # Find large files in the repository
          large_files=$(find . -type f -size +${MAX_SIZE}c -not -path './.git/*' 2>/dev/null || true)
          
          if [ -n "$large_files" ]; then
            echo "❌ ERROR: Large files detected!"
            echo "The following files exceed the $(($MAX_SIZE / 1024 / 1024))MB limit:"
            echo "$large_files" | while read file; do
              size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
              size_mb=$(($size / 1024 / 1024))
              echo "  - $file (${size_mb}MB)"
            done
            echo ""
            echo "Please remove these files or use Git LFS for large file storage."
            echo "Learn more: https://git-lfs.github.io/"
            exit 1
          else
            echo "✅ No large files detected. All files are within the size limit."
          fi

      - name: Check recent commits for large files
        run: |
          # Check only files in recent commits to catch new large files
          
          # Get list of files changed in this push/PR
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
          
          if [ -n "$changed_files" ]; then
            echo "Checking changed files for size violations..."
            echo "$changed_files" | while read file; do
              if [ -f "$file" ]; then
                size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
                if [ $size -gt $MAX_SIZE ]; then
                  size_mb=$(($size / 1024 / 1024))
                  echo "❌ ERROR: $file is ${size_mb}MB (exceeds limit)"
                  exit 1
                fi
              fi
            done
          fi
